server:
  port: 8082

spring:
  application:
    name: SUBMISSION-SERVICE
  data:
    mongodb:
#      uri: mongodb://localhost:27017/SUBMISSION
      uri: mongodb+srv://anvithsg2004:Ani%402004@cluster0.xf9on0f.mongodb.net/SUBMISSION?retryWrites=true&w=majority&appName=Cluster0&connectTimeoutMS=30000&timeoutMS=30000

eureka:
  instance:
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: https://service-registry-6oua.onrender.com/eureka/

