server:
  port: 8080

spring:
  application:
    name: USER-SERVICE
  data:
    mongodb:
      uri: mongodb://localhost:27017/USER

eureka:
  instance:
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
