server:
  port: 8081

spring:
  application:
    name: TASK-SERVICE
  data:
    mongodb:
#      uri: mongodb://localhost:27017/TASK
      uri: mongodb+srv://anvithsg2004:Ani%402004@cluster0.xf9on0f.mongodb.net/TASK?retryWrites=true&w=majority&appName=Cluster0&connectTimeoutMS=30000&timeoutMS=30000

eureka:
  instance:
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
